### PR TITLE
always show selected tasks in the filter. fixes #627

### LINKED ISSUE #627: Task displays in filter it shouldn't after editing
Steps to reproduce:

- add a task `text @a`
- filter to display tasks on list `a`
- edit the task to remove it from list `a`
  - it now reads just `task`
- Unselect the task via either back arrow or tapping it

Expected behavior: task disappears, since it does not match the filter criteria and is no longer selected.

Actual behavior: task persists in the view until you modify the filter.

### PR DESCRIPTION
**Pull request by smichel17**
Turns out when the active filter was changed, it wasn't loading with `showSelected = true`. Now it does.

### CODE REVIEW

File: src/main/java/nl/mpcjanssen/simpletask/AddTask.kt [hunk 1]
```diff
@@ -53,6 +53,9 @@ class AddTask : ThemedActionBarActivity() {
         // Config.loadTodoList(true)
 
         val intent = intent
+        val isEdit = intent.getBooleanExtra(Constants.EXTRA_EDIT, false)
+        if (!isEdit) TodoList.clearSelection()
+
```
Comment (smichel17) [inline src/main/java/nl/mpcjanssen/simpletask/AddTask.kt]: Unless it's an edit, clear the selection.

File: src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt [hunk 2]
```diff
@@ -199,14 +199,15 @@ class FilterActivity : ThemedNoActionBarActivity() {
...
-            }
+            R.id.menu_filter_action ->
+                if (asWidgetConfigure) {
+                    askWidgetName()
+                } else if (asWidgetReConfigure) {
+                    updateWidget()
+                    finish()
+                } else {
+                    applyFilter()
+                }
```
Comment (smichel17) [inline src/main/java/nl/mpcjanssen/simpletask/FilterActivity.kt]: Cosmetic change only, it was bugging me.

File: src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt [hunk 3]
```diff
@@ -62,6 +62,9 @@ import android.R.id as androidId
 
 class Simpletask : ThemedNoActionBarActivity() {
 
+    private const val EDIT: Boolean = true
+    private const val ADD: Boolean = false
+
```
Comment (smichel17) [inline src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt]: I didn't *need* to do this, but `startAddTaskActivity(EDIT)` makes a lot more sense than `startAddTaskActivity(true)`

File: src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt [hunk 4]
```diff
@@ -1020,8 +1025,8 @@ class Simpletask : ThemedNoActionBarActivity() {
             mFilter!!.saveInIntent(intent)
             setIntent(intent)
             mFilter!!.saveInPrefs(Config.prefs)
-            m_adapter!!.setFilteredTasks()
             closeDrawer(NAV_DRAWER)
+            closeSelectionMode()
```
Comment (smichel17) [inline src/main/java/nl/mpcjanssen/simpletask/Simpletask.kt]: `closeSelectionMode` calls `m_adapter!!.setFilteredTasks()`, so we don't need to do it twice.
